'use strict';
//http://newtriks.com/2013/11/29/environment-specific-configuration-in-angularjs-using-grunt/
//http://stackoverflow.com/questions/16930473/angularjs-factory-http-get-json-file
//http://mindthecode.com/how-to-use-environment-variables-in-your-angular-application/
//http://chariotsolutions.com/blog/post/angularjs-corner-using-promises-q-handle-asynchronous-calls/
angular.module('wfs-mobile.config', [])
.constant('configuration', {
    name: "WFS-App-Mobile",
    version: "0.0.1",
    environment: "PROD",
    lang: "fr",
    applicationMode: "MOCKUP",
    webServiceURL: "http://localhost:8080/wfs-rest/api/",
    dictionnary: {
        ACKNOWLEGMENT : "Acknowledged",
		ACKNOWLEGMENTSHORT : "Ack",
        ATP : "Market",
        BUY : "Buy",
        CANCELLED : "Cancelled",
		CANCELLEDSHORT : "Can",
        DAY : "Day",
        EXPIRED : "Expired",
		EXPIREDSHORT : "Exp",
        FUNDS : "Funds",
        GOOD_TILL_DATE : "GTD",
        OPCVMBUY : "Subscription",
        OPCVMBUYSHORT : "Subsc.",
        INDEX : "Index",
        LIMIT : "Lim",
        MARKET : "Market",
        MARKET_TO_LIMIT : "Market to limit",
        NEW : 'New',
		NEWSHORT : 'New',
        OPCVMSELLSHORT : "Sell",
        OPCVMSELL : "Sell",
		PARTIAL_EXECUTEDSHORT: "Part. exe.",
		PARTIAL_EXECUTED: "Partial execution",
        SELL : "Sell",
        STOCK : "Stock",
        STOP : "Stop",
        STOP_LIMIT : "Stop Limit",
        TRANSMITTED : "Transmitted",
		TRANSMITTEDSHORT : "Transmitted",
        4068 : "Limit price must be higher than stop price",
        4017 : "Expire date must be upper or equal to the current date",
        4021 : "Order quantity must be strictly positive",
        4031 : "Limit price must be provided",
        4033 : "Stop price must be provided",
        4056 : "The expiration date has been adjusted",
        4207 : "Too important order amount",
        4288 : "Shown quantity must be lower or equal to order quantity",
        4351 : "Max price variation between entered price and previous closing price exceeded",
        4358 : "Minimum quantity must be lower or equal to order quantity",
        5010 : "Buying Power Default",
        5011 : "Stock Positions Default",
        OUTDATED : "Outdated",
        WAITING : "Waiting",
        IN_PROGRESS : "In progress",
        EXECUTION : "Execution",
        EXPIRATION : "Expiration",
        REJECTION : "Rejection",
        MAIL : "Mail",
        SMS : "Text"
    }
});